version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./images:/usr/share/nginx/html/images
    networks:
      - webnet

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./images:/usr/share/nginx/html/images
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
